gmcli_env_vars:
  - key: GREYMATTER_API_HOST 
    value : 'localhost:5555'  
  - key: GREYMATTER_API_PREFIX 
    value : ''
  - key: GREYMATTER_API_SSL 
    value : 'false' 
  - key: GREYMATTER_API_INSECURE
    value : 'true'
  - key: GREYMATTER_API_SSLCERT 
    value : "/path/to/my.crt"
  - key: GREYMATTER_API_SSLCERT 
    value : "/path/to/my.key"
  - key: EDITOR 
    value : "vim"