---

# Create gm-catalog jsons
- hosts: tag_Name_gm_control_api_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-config
  vars:
    service_config: true
    global.service_name: gm-catalog
    cluster.port: 9080
    global.ssl_config_trust_file: /tmp/acert_dir/test-gm-catalog-leaf-authority.pem
    global.ssl_config_certificate_path: /tmp/acert_dir/test-gm-catalog-leaf-certificate.pem
    global.ssl_config_key_path: /tmp/acert_dir/test-gm-catalog-leaf-key.pem
  tags: gm-catalog, gm-catalog-jsons

# Run gm-catalog and its sidecar
- hosts: tag_Name_gm_catalog_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-catalog
  vars:
    CONTROL_SERVER_0_ADDRESS: 54.164.158.224
    XDS_HOST: 54.164.158.224
    XDS_CLUSTER: gm-catalog
  tags: gm-catalog