---

- hosts: tag_Name_gm_control_api_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-control-api
    - ansible-role-gmcli
    - ansible-role-jsons

- hosts: tag_Name_gm_control_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-control

- hosts: tag_Name_gm_proxy_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-proxy