---

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: ecs_services_ec2
    vars:
      aws_region: 'us-east-1'
      cluster_name: 'greymatter-ecs-cluster'
      control_ip: 'ip-192-168-13-230.ec2.internal'
      credentials_parameter: 'arn:aws:secretsmanager:us-east-1:269783025111:secret:ecs-greymatter-ci-w9Mvia'
      credentials_parameter_proxy: 'arn:aws:secretsmanager:us-east-1:269783025111:secret:ecs-greymatter-deciphernow-BlSqM8'
      ecs_instance_role: 'arn:aws:iam::269783025111:role/ecsInstanceRole'
      elb_control: 'internal-greymatter-ecs-alb-control-1675348944.us-east-1.elb.amazonaws.com'
      elb_control_api: 'internal-greymatter-ecs-alb-control-api-1758321780.us-east-1.elb.amazonaws.com'
      elb_data: 'internal-greymatter-ecs-alb-data-1110011196.us-east-1.elb.amazonaws.com'
      elb_jwt: 'internal-greymatter-ecs-alb-jwt-758070604.us-east-1.elb.amazonaws.com'
      # greymatter_proxy_image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.8.1'
      greymatter_proxy_image: 'deciphernow/gm-proxy:test'
      security_group: 'sg-09afc91307ea741df'
      subnet_list: 'subnet-0c9ebdfe0729ea3bc,subnet-0395f40638e417d83,subnet-0395f40638e417d83'
      task_target_group_control: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-control/0d12a52c3f1c30db'
      task_target_group_control_api: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-control-api/4ad9cf4700e45504'
      task_target_group_control_api_proxy:  'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-ctrl-api-pxy/df19ca343e5434cf'
      task_target_group_data: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-data/0184e76db2c1dd98'
      task_target_group_edge: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-edge/af0104643527a6ed'
      task_target_group_jwt: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-inst-jwt/c1da606dd9c535a3'
