---

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: ecs_services_ec2
    vars:
      aws_region: 'us-east-1'
      cluster_name: 'greymatter-ecs-cluster'
      control_ip: 'ip-192-168-95-32.ec2.internal'
      credentials_parameter: 'arn:aws:secretsmanager:us-east-1:706634194319:secret:ecs-greymatter-ci-emFEzR'
      credentials_parameter_proxy: 'arn:aws:secretsmanager:us-east-1:706634194319:secret:sofia-dockerhub-Xx7FIl'
      ecs_instance_role: 'arn:aws:iam::706634194319:role/ecsInstanceRole'
      elb_control: 'internal-greymatter-ecs-alb-control-789384777.us-east-1.elb.amazonaws.com'
      elb_control_api: 'internal-greymatter-ecs-alb-control-api-196872388.us-east-1.elb.amazonaws.com'
      elb_data: 'internal-greymatter-ecs-alb-data-153575526.us-east-1.elb.amazonaws.com'
      elb_jwt: 'internal-greymatter-ecs-alb-jwt-1368369169.us-east-1.elb.amazonaws.com'
      # greymatter_proxy_image: 'docker.greymatter.io/release/deciphernow/gm-proxy:0.8.1'
      greymatter_proxy_image: 'deciphernow/gm-proxy:http2'
      security_group: 'sg-058ff37fcba82d64e'
      subnet_list: 'subnet-0e06fb4f956d9f5f8,subnet-0e06fb4f956d9f5f8,subnet-0e06fb4f956d9f5f8'
      task_target_group_control: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-control/86b74645a19ae920'
      task_target_group_control_api: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-control-api/fe63a9ec40ef7820'
      task_target_group_control_api_proxy:  'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-ctrl-api-pxy/b136b8bdfabeffa3'
      task_target_group_data: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-data/556db1b39e0c1990'
      task_target_group_edge: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-edge/5ebfa16da4af3994'
      task_target_group_jwt: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-inst-jwt/c4cc3b6ae501f94a'
