---

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: ecs_services_fargate
    vars:
      aws_region: 'us-east-1'
      cluster_name: 'greymatter-ecs-cluster'
      credentials_parameter_prod: 'arn:aws:secretsmanager:us-east-1:269783025111:secret:ecs-greymatter-ci-w9Mvia'
      credentials_parameter_deciphernow: 'arn:aws:secretsmanager:us-east-1:269783025111:secret:ecs-greymatter-deciphernow-BlSqM8'
      ecs_instance_role: 'arn:aws:iam::269783025111:role/ecsInstanceRole'
      elb_control: 'internal-greymatter-ecs-alb-control-1675348944.us-east-1.elb.amazonaws.com'
      elb_control_api: 'internal-greymatter-ecs-alb-control-api-1758321780.us-east-1.elb.amazonaws.com'
      greymatter_proxy_image: 'deciphernow/gm-proxy:test'
      security_group: 'sg-09afc91307ea741df'
      subnet_list: 'subnet-0c9ebdfe0729ea3bc,subnet-0395f40638e417d83,subnet-0395f40638e417d83'
      task_target_group_control: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-ip-control/ff8833ad5fcacd4f'
      task_target_group_control_api: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-ip-control-api/3582a62bf65ed0f4'
      task_target_group_edge: 'arn:aws:elasticloadbalancing:us-east-1:269783025111:targetgroup/gm-ecs-alb-tg-ip-edge/654f974d7396eb5c'
