systemd_service: 'gm-jwt-security'

nexus_repo_url: "https://nexus.production.deciphernow.com"
nexus_repo: "repository/raw-dev/greymatter"
nexus_tar_file: "gm-jwt-security-1.0.1.tar.gz"

service_env_vars:
  - key: USERS_JSON 
    value : ewogICJ1c2VycyI6IFsKICAgIHsKICAgICAgImxhYmVsIjogInJvYiIsCiAgICAgICJ2YWx1ZXMiOiB7CiAgICAgICAgImVtYWlsIjogWwogICAgICAgICAgInJvYi5maWVsZGluZ0BkZWNpcGhlcm5vdy5jb20iCiAgICAgICAgXSwKICAgICAgICAib3JnIjogWwogICAgICAgICAgInd3dy5kZWNpcGhlcm5vdy5jb20iCiAgICAgICAgXQogICAgICB9CiAgICB9LAogICAgewogICAgICAibGFiZWwiOiAiZGFuaWVsIiwKICAgICAgInZhbHVlcyI6IHsKICAgICAgICAiZW1haWwiOiBbCiAgICAgICAgICAiZGFuaWVsLmNveEBkZWNpcGhlcm5vdy5jb20iCiAgICAgICAgXSwKICAgICAgICAib3JnIjogWwogICAgICAgICAgInd3dy5kZWNpcGhlcm5vdy5jb20iCiAgICAgICAgXQogICAgICB9CiAgICB9LAogICAgewogICAgICAibGFiZWwiOiAiaGlyb21pIiwKICAgICAgInZhbHVlcyI6IHsKICAgICAgICAiZW1haWwiOiBbCiAgICAgICAgICAiaGlyb21pLnN1ZW5hZ2FAZGVjaXBoZXJub3cuY29tIgogICAgICAgIF0sCiAgICAgICAgIm9yZyI6IFsKICAgICAgICAgICJ3d3cuZGVjaXBoZXJub3cuY29tIgogICAgICAgIF0KICAgICAgfQogICAgfSwKICAgIHsKICAgICAgImxhYmVsIjogIm1hcnRpbiIsCiAgICAgICJ2YWx1ZXMiOiB7CiAgICAgICAgImVtYWlsIjogWwogICAgICAgICAgIm1hcnRpbi50ZXJza2luQGRlY2lwaGVybm93LmNvbSIKICAgICAgICBdLAogICAgICAgICJvcmciOiBbCiAgICAgICAgICAid3d3LmRlY2lwaGVybm93LmNvbSIKICAgICAgICBdCiAgICAgIH0KICAgIH0KICBdCn0=
  - key: PRIVATE_KEY 
    value : LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JSGNBZ0VCQkVJQkhRY01yVUh5ZEFFelNnOU1vQWxneFF1a3lqQTROL2laa21ETVIvdFRkVmg3U3hNYk8xVE4KeXdzRkJDdTYvZEZXTE5rUDJGd1FFQmtqREpRZU9mc3hKZWlnQndZRks0RUVBQ09oZ1lrRGdZWUFCQUJEWklJeAp6a082cWpkWmF6ZG1xWFg1dnRFcWtodzlkcVREeTN6d0JkcXBRUmljWDRlS2lZUUQyTTJkVFJtWk0yZE9FRHh1Clhja0hzcVMxZDNtWHBpcDh2UUZHTWJCM1hRVm9DZWN0SUlLMkczRUlwWmhGZFNGdG1sa2t5U1N4angzcS9UcloKaVlRTjhJakpPbUNueUdXZ1VWUkdERURiNWlZdkZXc3dpSkljSWYyOGVRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  - key: BIND_ADDRESS 
    value : 0.0.0.0  
  - key: HTTP_PORT
    value : 8080
  - key: HTTPS_PORT 
    value : 9443
  - key: TOKEN_EXP_TIME 
    value : 28800
  - key: REDIS_HOST 
    value : 127.0.0.1
  - key: REDIS_PORT 
    value : 6379
  - key: REDIS_DB 
    value : 15
  - key: REDIS_PASS 
    value : password123
  - key: JWT_API_KEY 
    value : MTIzCg==
  - key: ENABLE_TLS
    value : "false"
  - key: SERVER_TRUST
    value :
  - key: SERVER_CERT
    value :
  - key: SERVER_KEY
    value :
  - key: ZEROLOG_LEVEL
    value : info