---

  - name: EFS provisioning for volumes
    efs:
      name: certificateDump
      state: present
      tags:
        name: certs
        purpose: volume-mounting
      targets:
        - subnet_id: "subnet-0e06fb4f956d9f5f8"
          security_groups: [ "sg-058ff37fcba82d64e" ]
    register: efs_volumes
