---

  - name: set image id fact
      set_fact:
        ecs_image_id: "ami-035a1bdaf0e4bf265"

  - name: provision ec2 instance to create an image
      ec2:
        key_name: 'enter-ecs'
        instance_type: t2.medium
        state: present
        image: '{{ ecs_image_id }}'
        wait: yes
        user_data: "{{ user_data }}"
        instance_profile_name: ecsInstanceRole
        instance_tags:
          Name: '{{ resource_prefix }}_ecs_agent'
        group_id: '{{ setup_sg.group_id }}'
        vpc_subnet_id: '{{ setup_subnet.results[0].subnet.id }}'
      register: setup_instance
