systemd_service: 'gm-control'

service_env_vars:
  - key: GM_CONTROL_CONSOLE_LEVEL 
    value : info  
  - key: GM_CONTROL_API_KEY 
    value : xxxx
  - key: GM_CONTROL_API_ZONE_NAME 
    value : default-zone  
  - key: GM_CONTROL_API_SSL 
    value : false
  - key: GM_CONTROL_API_HOST 
    value : 18.206.39.107:5555
  - key: GM_CONTROL_CMD 
    value : "aws"
  - key: GM_CONTROL_FILE_FORMAT 
    value : yaml
  - key: GM_CONTROL_FILE_FILENAME 
    value : /app/routes.yaml  
  - key: GM_CONTROL_XDS_RESOLVE_DNS 
    value : true
  - key: GM_CONTROL_XDS_ADS_ENABLED 
    value : true