- name: Create json config direcory
  file:
    path: "{{ jsons_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  tags: jsons

- name: Create json configs
  template:
    src: "{{ item.0 }}"
    dest: "{{ jsons_dir }}/{{ item.1 }}.json"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  loop: "{{ jsons }}"
  tags: jsons
  
- name: Create greymatter objects using the json configs
  shell: |
    greymatter create {{ item.2 }} < {{ jsons_dir }}/{{ item.1 }}.json
    exit 0
  loop: "{{ jsons }}"
  tags: jsons