---

- name: Create and run gm-control binary as a service
  include_role:
    name: ansible-role-systemd
    public: yes
    apply:
      tags:
        - control
  when: ( ansible_distribution == 'Ubuntu' )
  tags: control