- name: Create Service group
  group:
    name: "{{ service_group }}"
    state: present
    system: yes
  tags: prepare

- name: Creating Service User
  user:
    name: "{{ service_user }}"
    groups: "{{ service_group }}"
    system: yes
    append: yes
  tags: prepare

- name: Run apt update
  apt:
    update_cache: yes
  tags: prepare

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
  tags: prepare