---

  - name: create greymatter ro secret in AWS secrets manager
    aws_secret:
      name: "ecs-greymatter-ci"
      description: "read only secret to the greymatter nexus repo"
      state: present
      secret_type: 'string'
      secret: "{{ greymatter_ro_secret | to_json }}"
    register: ecs_greymatter_ci_secret

  - name: create jwt secret in AWS secrets manager
    aws_secret:
      name: "jwt-secret"
      description: "secret values for gm-jwt-security"
      state: present
      secret_type: 'string'
      secret: "{{ jwt_secret | to_json }}"
    register: jwt_secret

  - name: create data secret in AWS secrets manager
    aws_secret:
      name: "data-secret"
      description: "secret values for gm-data"
      state: present
      secret_type: 'string'
      secret: "{{ data_secret | to_json }}"
    register: data_secret

  - name: create slo secret in AWS secrets manager
    aws_secret:
      name: "slo-psql-pass"
      description: "psql pass for gm-slo"
      state: present
      secret_type: 'string'
      secret: "{{ slo_psql_pass }}"
    register: slo_psql_pass

  - name: create sense secret in AWS secrets manager
    aws_secret:
      name: "sense-oc-api-token"
      description: "OC api token for gm-sense"
      state: present
      secret_type: 'string'
      secret: "{{ sense_oc_api_token }}"
    register: sense_oc_api_token

  - name: create base64 sidecar cert b64 secret in AWS secrets manager
    aws_secret:
      name: "sidecar-certs-cert-b64"
      description: "base64 sidecar certs"
      state: present
      secret_type: 'binary'
      secret: "{{ sidecar_certs_cert_b64 | to_json }}"
    register: sidecar_certs

  - name: create base64 sidecar key secret in AWS secrets manager
    aws_secret:
      name: "sidecar-certs-key-b64"
      description: "base64 sidecar certs"
      state: present
      secret_type: 'binary'
      secret: "{{ sidecar_certs_key_b64 | to_json }}"
    register: sidecar_certs

  - name: create base64 sidecar server b64 secret in AWS secrets manager
    aws_secret:
      name: "sidecar-certs-server-b64"
      description: "base64 sidecar certs"
      state: present
      secret_type: 'binary'
      secret: "{{ sidecar_certs_server_b64 | to_json }}"
    register: sidecar_certs

  - name: create base64 sidecar server key b64 secret in AWS secrets manager
    aws_secret:
      name: "sidecar-certs-server-key-b64"
      description: "base64 sidecar certs"
      state: present
      secret_type: 'binary'
      secret: "{{ sidecar_certs_server_key_b64 | to_json }}"
    register: sidecar_certs

  - name: create base64 sidecar cert ca secrets in AWS secrets manager
    aws_secret:
      name: "sidecar-certs-ca"
      description: "base64 sidecar certs"
      state: present
      secret_type: 'binary'
      secret: "{{ sidecar_certs_ca | to_json }}"
    register: sidecar_certs
