---

  - name: create greymatter ro secret in AWS secrets manager
    aws_secret:
      name: "ecs-greymatter-ci"
      description: "read only secret to the greymatter nexus repo"
      state: present
      secret_type: 'string'
      secret: "{{ greymatter_ro_secret | to_json }}"
    register: ecs_greymatter_ci_secret

  - name: create jwt secret in AWS secrets manager
    aws_secret:
      name: "jwt-secret"
      description: "secret values for gm-jwt-security"
      state: present
      secret_type: 'string'
      secret: "{{ jwt_secret | to_json }}"
    register: jwt_secret

  - name: create data secret in AWS secrets manager
    aws_secret:
      name: "data-secret"
      description: "secret values for gm-data"
      state: present
      secret_type: 'string'
      secret: "{{ data_secret | to_json }}"
    register: data_secret

  - name: create slo secret in AWS secrets manager
    aws_secret:
      name: "slo-psql-pass"
      description: "psql pass for gm-slo"
      state: present
      secret_type: 'string'
      secret: "{{ slo_psql_pass }}"
    register: slo_psql_pass

  - name: create sense secret in AWS secrets manager
    aws_secret:
      name: "sense-oc-api-token"
      description: "OC api token for gm-sense"
      state: present
      secret_type: 'string'
      secret: "{{ sense_oc_api_token }}"
    register: sense_oc_api_token