---

- name: Create and run gm-jwt-security binary as a service
  include_role:
    name: ansible-role-systemd
    public: yes
    apply:
      tags:
        - ijwt
  when: ( ansible_distribution == 'Ubuntu' )
  tags: ijwt