---

# Restart redis server. Otherwise get connection error
- name: Restart Redis server
  service: 
    name: redis-server
    state: restarted 
  tags: ijwt

- name: Create and run gm-jwt-security binary as a service
  include_role:
    name: ansible-role-systemd
    public: yes
    apply:
      tags:
        - ijwt
  when: ( ansible_distribution == 'Ubuntu' )
  tags: ijwt