- name: Create Service Directory
  file:
    path: "{{ cli_download_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  tags: gmcli

- name: Download cli Tar
  get_url:
    url: "{{ gm_cli_nexus_repo_url }}/{{ gm_cli_nexus_repo }}/{{ gm_cli_nexus_tar_file }}"
    dest: "{{ cli_download_dir }}"
    username: '{{ nexus_user }}'
    password: '{{ nexus_pw }}'
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0655'
  tags: gmcli

- name: Extract cli Tar
  unarchive:
    src: "{{ cli_download_dir }}/{{ gm_cli_nexus_tar_file }}"
    dest: "{{ cli_download_dir }}"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
  tags: gmcli

- name: Copy service files from local to server
  copy:
    src: "{{ cli_download_dir }}/greymatter.linux"
    dest: "{{ cli_home_dir }}/greymatter"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: u=rx,g=rx,o=rx
    remote_src: yes
  tags: gmcli

- name: Add gmcli Env Vars
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ gmcli_env_vars }}"
  tags: gmcli