---

  - name: Create task definition edge
    ecs_taskdefinition:
      state: present
      family: "greymatter-edge"
      network_mode: awsvpc
      launch_type: FARGATE
      cpu: 512
      memory: 1024
      region: "{{ aws_region }}"
      execution_role_arn: "{{ ecs_instance_role }}"
      task_role_arn: "{{ ecs_instance_role }}"
      containers:
      - name: edge
        secrets:
        - name: INGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-cert-b64-GvrspG
        - name: INGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-key-b64-m46Nvr
        - name: EGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-server-b64-uIFYGU
        - name: EGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-server-key-b64-L0xcew
        - name: EGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-ca-oyDcNY
        - name: INGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-ca-oyDcNY
        essential: true
        image: "{{ greymatter_proxy_image }}"
        repositoryCredentials:
          credentialsParameter: "{{ credentials_parameter_deciphernow }}"
        dockerLabels:
           gm-cluster: "edge:8081"
        environment:
        - name: "ENVOY_ADMIN_LOG_PATH"
          value: "/dev/stdout"
        - name: "PROXY_DYNAMIC"
          value: "true"
        - name: "XDS_CLUSTER"
          value: edge
        - name: "XDS_HOST"
          value: "{{ elb_control }}"
        - name: "XDS_PORT"
          value: 50000
        - name: "XDS_NODE_ID"
          value: "default-node"
        portMappings:
        - containerPort: 22
          hostPort: 22
          protocol: tcp
        - containerPort: 42
          hostPort: 42
        - containerPort: 80
          hostPort: 80
          protocol: tcp
        - containerPort: 8081
          hostPort: 8081
          protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: openjobs
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: web
    register: task_output
  
  - name: ECS service edge
    ecs_service:
      state: present
      name: edge
      cluster: "{{ cluster_name }}"
      region: "{{ aws_region }}"
      launch_type: FARGATE
      task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
      desired_count: 1
      network_configuration:
        assign_public_ip: true
        security_groups: "{{ security_group }}"
        subnets: "{{ subnet_list }}"
      load_balancers:
        - targetGroupArn: "{{ task_target_group_edge }}"
          containerName: "edge"
          containerPort: 8081
    register: "ecs_service"
  
