---

  - name: Create task definition catalog
    ecs_taskdefinition:
      state: present
      family: "greymatter-catalog"
      network_mode: awsvpc
      launch_type: FARGATE
      cpu: 512
      memory: 1024
      region: "{{ aws_region }}"
      execution_role_arn: "{{ ecs_instance_role }}"
      task_role_arn: "{{ ecs_instance_role }}"
      volumes:
      - name: certs
      containers:
      - name: "proxy-catalog"
        essential: true
        image: "{{ greymatter_proxy_image }}"
        repositoryCredentials:
          credentialsParameter: "{{ credentials_parameter }}"
        dockerLabels:
          gm-cluster: "catalog:8080"
        secrets:
        - name: INGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-cert-b64-ZCdDOo
        - name: INGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-key-b64-jRhKhv
        - name: EGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-server-b64-nf57aF
        - name: EGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-server-key-b64-EwBU9t
        - name: EGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-ca-7w0voA
        - name: INGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-ca-7w0voA
        environment:
        - name: "ENVOY_ADMIN_LOG_PATH"
          value: "/dev/stdout"
        - name: "PROXY_DYNAMIC"
          value: "true"
        - name: "XDS_CLUSTER"
          value: catalog
        - name: "XDS_HOST"
          value: "{{ elb_control }}" # todo point to gm-control
        - name: "XDS_PORT"
          value: 50000
        - name: "XDS_NODE_ID"
          value: "default-node"
        portMappings:
        - containerPort: 9080
          hostPort: 9080
          protocol: tcp
        - containerPort: 8081
          hostPort: 8081
          protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: openjobs
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: web
        mountPoints:
        - containerPath: "/etc/pki"
          sourceVolume: certs
      - name: catalog
        essential: false
        image: "docker.production.deciphernow.com/deciphernow/gm-catalog:1.0.1"
        repositoryCredentials:
          credentialsParameter: "{{ credentials_parameter }}"
        secrets:
        - name: "CLIENT_CERT"
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-server-b64-nf57aF
        - name: "CLIENT_KEY"
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-key-b64-jRhKhv
        - name: "CLIENT_TRUST"
          valueFrom: arn:aws:secretsmanager:us-east-1:706634194319:secret:sidecar-certs-ca-7w0voA
        environment:
        - name: "CA_CERT_PATH"
          value: "/etc/pki/ca.crt"
        - name: "CLIENT_CN"
          value: "di2e.test"
        - name: "CLIENT_EMAIL"
          value: "gm-control@deciphernow.com"
        - name: "DEBUG"
          value: "true"
        - name: "CONTROL_SERVER_0_ADDRESS"
          value: "{{ elb_control }}:50000"
        - name: "CONTROL_SERVER_0_REQUEST_CLUSTER_NAME"
          value: edge
        - name: "CONTROL_SERVER_0_ZONE_NAME"
          value: "default-zone"
        - name: "CONFIG_SOURCE"
          value: gmdata
        - name: "CLIENT_ADDRESS"
          value: localhost
        - name: "CLIENT_PORT"
          value: 9080
        - name: "CLIENT_PREFIX"
          value: "/data"
        - name: "GMDATA_STARTUP_DELAY"
          value: 10s
        - name: "GMDATA_MAX_RETRIES"
          value: 100
        - name: "GMDATA_RETRY_DELAY"
          value: 5s
        - name: "GMDATA_ROOT_EVENT_NAME"
          value: world
        - name: "CLIENT_USE_TLS"
          value: "true"
        - name: "CLIENT_IDENTITY"
          value: "CN=localhost,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US"
        - name: "CLIENT_EMAIL"
          value: "localhost@deciphernow.com"
        - name: "SERVER_CERT_PATH"
          value: "/etc/pki/server.crt"
        - name: "SERVER_KEY_PATH"
          value: "/etc/pki/server.key"
        - name: "USE_TLS"
          value: "true"
        portMappings:
        - containerPort: 8080
          hostPort: 8080
          protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: openjobs
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: web
        volumesFrom:
        - sourceContainer: "proxy-catalog"
    register: task_output

  - name: ECS service catalog
    ecs_service:
      state: present
      name: catalog
      cluster: "{{ cluster_name }}"
      region: "{{ aws_region }}"
      launch_type: FARGATE
      task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
      desired_count: 1
      network_configuration:
        assign_public_ip: true
        security_groups: "{{ security_group }}"
        subnets: "{{ subnet_list }}"
    register: "ecs_service"
