---

  - name: Create task definition control-api
    ecs_taskdefinition:
      state: present
      family: "greymatter-control-api"
      network_mode: "awsvpc"
      launch_type: "EC2"
      execution_role_arn: "{{ ecs_instance_role }}"
      task_role_arn: "{{ ecs_instance_role }}"
      containers:
      - name: control-api
        cpu: 256
        essential: true
        image: "{{ greymatter_proxy_image }}"
        repositoryCredentials:
          credentialsParameter: "arn:aws:secretsmanager:us-east-2:151736245382:secret:ecs-greymatter/zGREYMATTER-ci-6WOFGP"
        memory: 400
        environment:
        - name: "GM_CONTROL_API_ADDRESS"
          value: "0.0.0.0:5555"
        - name: "GM_CONTROL_API_LOG_LEVEL"
          value: "debug"
        - name: "GM_CONTROL_API_ORG_KEY"
          value: "deciphernow"
        - name: "GM_CONTROL_API_PERSISTER_PATH"
          value: "app/control-api/data/backend.json"
        - name: "GM_CONTROL_CMD"
          value: "ecs"
        - name: "GM_CONTROL_API_PERSISTER_TYPE"
          value: "null"
        - name: "GM_CONTROL_API_ZONE_KEY"
          value: "default-zone"
        portMappings:
        - containerPort: 5555
          hostPort: 5555
          protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: openjobs
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: web
    register: task_output

  - name: ECS service control api
    ecs_service:
      state: present
      name: control-api
      network_configuration:
        security_groups: "{{ security_group }}"
        subnets: "{{ subnet_list }}"
      cluster: "{{ cluster_name }}"
      task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
      desired_count: 1
      load_balancers:
        - targetGroupArn: "{{ task_target_group }}"
          containerName: "control-api"
          containerPort: "5555"
    register: "ecs_service"
